import "src\\ViewModels\\EventLogsViewModel.idl";

namespace AstralChronicle
{
    runtimeclass EventLogsPage : Microsoft.UI.Xaml.Controls.Page
    {
        EventLogsPage();
        EventLogsViewModel ViewModel{ get; };
    }
}
