// Created by EternityBoundary on Jul 20,2026
#include "pch.h"
#include "SessionsPage.xaml.h"
#include "SessionsPage.g.cpp"
#include <wil/cppwinrt_helpers.h>
#include <winrt/Windows.Storage.h>
namespace winrt::AstralChronicle::implementation
{
    SessionsPage::SessionsPage():m_viewModel(winrt::make<SessionsViewModel>()){InitializeComponent();} winrt::AstralChronicle::SessionsViewModel SessionsPage::ViewModel()const{return m_viewModel;}
    void SessionsPage::Initialize(::AstralChronicle::services::ISessionRepository&r,::AstralChronicle::design::IStringResourceService const&s){winrt::get_self<SessionsViewModel>(m_viewModel)->Initialize(r,s,PageRoot().DispatcherQueue());}
    void SessionsPage::OnNewClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->NewSession();}void SessionsPage::OnSaveClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Save();}void SessionsPage::OnResumeClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Resume();}void SessionsPage::OnPinClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->TogglePin();}void SessionsPage::OnDuplicateClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Duplicate();}void SessionsPage::OnArchiveClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Archive();}void SessionsPage::OnDeleteClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Delete();}void SessionsPage::OnRefreshClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Refresh();}
    void SessionsPage::OnExportClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){auto t=winrt::get_self<SessionsViewModel>(m_viewModel)->ExportText();if(!t.empty())ExportAsync(t);}void SessionsPage::OnImportClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){ImportAsync();}
    winrt::fire_and_forget SessionsPage::ExportAsync(winrt::hstring text){auto l=get_strong();co_await winrt::resume_background();try{auto f=winrt::Windows::Storage::ApplicationData::Current().LocalFolder();auto file=co_await f.CreateFileAsync(L"Sessions-export.txt",winrt::Windows::Storage::CreationCollisionOption::ReplaceExisting);co_await winrt::Windows::Storage::FileIO::WriteTextAsync(file,text);}catch(...){} }
    winrt::fire_and_forget SessionsPage::ImportAsync(){auto l=get_strong();auto d=PageRoot().DispatcherQueue();winrt::hstring t;co_await winrt::resume_background();try{auto f=winrt::Windows::Storage::ApplicationData::Current().LocalFolder();auto i=co_await f.TryGetItemAsync(L"Sessions-import.txt");if(i)t=co_await winrt::Windows::Storage::FileIO::ReadTextAsync(i.as<winrt::Windows::Storage::StorageFile>());}catch(...){}co_await wil::resume_foreground(d);if(!t.empty())winrt::get_self<SessionsViewModel>(m_viewModel)->ImportText(t);}
}
