// Created by EternityBoundary on Jul 20,2026
#include "pch.h"
#include "SessionsPage.xaml.h"
#include "SessionsPage.g.cpp"
#include "DesignSystem/Localization/IStringResourceService.h"
#include <wil/cppwinrt_helpers.h>
#include <winrt/Microsoft.UI.Content.h>
#include <winrt/Microsoft.Windows.Storage.Pickers.h>
#include <filesystem>
#include <fstream>
#include <sstream>
namespace winrt::AstralChronicle::implementation
{
    SessionsPage::SessionsPage():m_viewModel(winrt::make<SessionsViewModel>()){InitializeComponent();} winrt::AstralChronicle::SessionsViewModel SessionsPage::ViewModel()const{return m_viewModel;}
    void SessionsPage::Initialize(std::shared_ptr<::AstralChronicle::services::ISessionRepository> repository,std::shared_ptr<::AstralChronicle::design::IStringResourceService> strings){m_strings=strings;winrt::get_self<SessionsViewModel>(m_viewModel)->Initialize(std::move(repository),std::move(strings),PageRoot().DispatcherQueue());}
    void SessionsPage::OnNewClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->NewSession();}void SessionsPage::OnSaveClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Save();}void SessionsPage::OnResumeClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Resume();}void SessionsPage::OnPinClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->TogglePin();}void SessionsPage::OnDuplicateClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Duplicate();}void SessionsPage::OnArchiveClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Archive();}void SessionsPage::OnDeleteClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Delete();}void SessionsPage::OnRefreshClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){winrt::get_self<SessionsViewModel>(m_viewModel)->Refresh();}
    void SessionsPage::OnExportClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){auto t=winrt::get_self<SessionsViewModel>(m_viewModel)->ExportText();if(!t.empty())ExportAsync(t,PageRoot().XamlRoot().ContentIslandEnvironment().AppWindowId());}void SessionsPage::OnImportClicked(winrt::Windows::Foundation::IInspectable const&,Microsoft::UI::Xaml::RoutedEventArgs const&){ImportAsync(PageRoot().XamlRoot().ContentIslandEnvironment().AppWindowId());}
    void SessionsPage::OnChannelsChanged(winrt::Windows::Foundation::IInspectable const& sender,Microsoft::UI::Xaml::Controls::SelectionChangedEventArgs const&){auto const combo=sender.as<Microsoft::UI::Xaml::Controls::ComboBox>();if(!combo.SelectedValue())return;try{winrt::get_self<SessionsViewModel>(m_viewModel)->EditorChannels(winrt::unbox_value<winrt::hstring>(combo.SelectedValue()));}catch(...){} }
    winrt::fire_and_forget SessionsPage::ExportAsync(winrt::hstring text,winrt::Microsoft::UI::WindowId windowId){try{auto l=get_strong();auto const strings=m_strings;Microsoft::Windows::Storage::Pickers::FileSavePicker picker{windowId};picker.SuggestedStartLocation(Microsoft::Windows::Storage::Pickers::PickerLocationId::DocumentsLibrary);picker.SuggestedFileName(strings?strings->GetString(L"Sessions.ExportSuggestedFileName.Text"):winrt::hstring{L"Sessions-export"});picker.DefaultFileExtension(L".txt");auto const fileTypes=winrt::single_threaded_vector<winrt::hstring>();fileTypes.Append(L".txt");picker.FileTypeChoices().Insert(strings?strings->GetString(L"Sessions.ExportTextFiles.Text"):winrt::hstring{L"Text files (*.txt)"},fileTypes);auto const result=co_await picker.PickSaveFileAsync();if(result){auto const path=result.Path();co_await winrt::resume_background();auto const content=winrt::to_string(text);std::ofstream output{std::filesystem::path{path.c_str()},std::ios::binary|std::ios::trunc};if(!output)throw winrt::hresult_error{E_FAIL};output.write(content.data(),static_cast<std::streamsize>(content.size()));if(!output)throw winrt::hresult_error{E_FAIL};}}catch(...){} }
    winrt::fire_and_forget SessionsPage::ImportAsync(winrt::Microsoft::UI::WindowId windowId){try{auto l=get_strong();auto d=PageRoot().DispatcherQueue();Microsoft::Windows::Storage::Pickers::FileOpenPicker picker{windowId};picker.SuggestedStartLocation(Microsoft::Windows::Storage::Pickers::PickerLocationId::DocumentsLibrary);picker.FileTypeFilter().Append(L".txt");auto const result=co_await picker.PickSingleFileAsync();if(!result)co_return;auto const path=result.Path();co_await winrt::resume_background();std::ifstream input{std::filesystem::path{path.c_str()},std::ios::binary|std::ios::ate};if(!input)throw winrt::hresult_error{E_FAIL};constexpr std::streamoff maxImportBytes=4*1024*1024;auto const size=input.tellg();if(size<=0||size>maxImportBytes)co_return;input.seekg(0,std::ios::beg);std::string content(static_cast<std::size_t>(size),'\0');input.read(content.data(),static_cast<std::streamsize>(content.size()));if(!input)throw winrt::hresult_error{E_FAIL};if(content.size()>=3&&static_cast<unsigned char>(content[0])==0xEF&&static_cast<unsigned char>(content[1])==0xBB&&static_cast<unsigned char>(content[2])==0xBF)content.erase(0,3);if(content.size()>=2&&((static_cast<unsigned char>(content[0])==0xFF&&static_cast<unsigned char>(content[1])==0xFE)||(static_cast<unsigned char>(content[0])==0xFE&&static_cast<unsigned char>(content[1])==0xFF)))co_return;auto const decoded=winrt::to_hstring(content);co_await wil::resume_foreground(d);if(!decoded.empty())winrt::get_self<SessionsViewModel>(m_viewModel)->ImportText(decoded);}catch(...){} }
}
