import "src\\ViewModels\\SettingsViewModel.idl";

namespace AstralChronicle
{
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
        SettingsViewModel ViewModel{ get; };
        Microsoft.UI.Xaml.Controls.RadioButtons LanguageRadioButtons{ get; };
        Microsoft.UI.Xaml.Controls.ScrollViewer PageRoot{ get; };
        Microsoft.UI.Xaml.Controls.StackPanel PageContent{ get; };
    }
}
